name: commerce_kickstart
recipe: drupal9
config:
  webroot: web
  php: '8.0'
  via: nginx
  database: mariadb:10.4
  xdebug: true

services:
  appserver:
    overrides:
      environment:
        # Enable PHPStorm XDebug with CLI.
        PHP_IDE_CONFIG: "serverName=commerce_kickstart.local"
        DRUSH_OPTIONS_URI: "https://commerce_kickstart.lndo.site"

  mailhog:
    type: mailhog:v1.0.0
    portforward: false
    hogfrom:
      - appserver

tooling:

  install:
    service: appserver
    description: Install Application
    cmd:
      - /bin/sh -c "if [ -d web/sites/default ]; then chmod -R +w web/sites/default; fi"
      - cd "$LANDO_MOUNT" && composer --no-ansi --no-interaction install --no-progress --prefer-dist --optimize-autoloader
      - cd "$LANDO_WEBROOT" && drush -y si commerce_kickstart --site-name='Commerce Kickstart' --site-mail='admin@example.com' --account-name='system' --account-mail='system@example.com' --account-pass='system'
      - cd "$LANDO_WEBROOT" && drush ucrt admin --password="admin" --mail="admin@example.com"
      - cd "$LANDO_WEBROOT" && drush urol "administrator" admin

  devel:
    service: appserver
    description: Enable devel systems
    cmd: true
      - cd "$LANDO_WEBROOT" && drush -y en devel field_ui views_ui menu_ui features_ui dblog contextual webprofiler masquerade

  demo:
    service: appserver
    description: Enable devel systems
    cmd: true
      - cd "$LANDO_WEBROOT" && drush -y en commerce_demo

  update:
    service: appserver
    description: Update Application
    cmd:
      - /bin/sh -c "if [ -d web/sites/default ]; then chmod -R +w web/sites/default; fi"
      - cd "$LANDO_MOUNT" && composer update
      - cd "$LANDO_WEBROOT" && drush -y updb

  phpunit:
    service: appserver
    description: PHP Unit Tests
    cmd:
      - cd "$LANDO_MOUNT" && ./bin/phpunit

  phpstan:
    service: appserver
    description: PhpStan
    cmd:
      - cd "$LANDO_MOUNT" && ./bin/phpstan analyse .

  phpcs:
    service: appserver
    description: PHP Code Sniffer
    cmd:
      - cd "$LANDO_MOUNT" && ./bin/phpcs

  soften:
    service: appserver
    description: Soften the Drupal codebase
    cmd:
      - /bin/sh -c "if [ -d web/sites/default ]; then chmod -R +w web/sites/default; fi"
