<?php

/**
 * @file
 * Contains functions for Kickstart License.
 */

/**
 * Implements hook_modules_installed().
 */
function commerce_kickstart_license_modules_installed($modules, $is_syncing) {
  $config_factory = \Drupal::configFactory();

  if (!$is_syncing && in_array('commerce_shipping', $modules) && in_array('commerce_checkout.commerce_checkout_flow.shipping', $config_factory->listAll('commerce_checkout'))) {
    $config = $config_factory->getEditable("commerce_checkout.commerce_checkout_flow.shipping");
    $config->set('configuration.panes.login.allow_guest_checkout', FALSE);
    $config->set('configuration.panes.login.allow_registration', TRUE);
    $config->set('configuration.panes.completion_register.step', '_disabled');
    $config->save();
  }
}
